/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppAchievementsRouteImport } from './routes/_app.achievements'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppMentorRouteImport } from './routes/_app.mentor'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppLearningIndexRouteImport } from './routes/_app.learning.index'
import { Route as AppPracticeIndexRouteImport } from './routes/_app.practice.index'
import { Route as AppPracticeChallengeIdRouteImport } from './routes/_app.practice.$challengeId'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsSlugRouteImport } from './routes/_app.projects.$slug'
import { Route as AppLearningSubjectIndexRouteImport } from './routes/_app.learning.$subject.index'
import { Route as AppLearningSubjectTopicIdRouteImport } from './routes/_app.learning.$subject.$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorRoute = AppMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningIndexRoute = AppLearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeIndexRoute = AppPracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeChallengeIdRoute = AppPracticeChallengeIdRouteImport.update({
  id: '/practice/$challengeId',
  path: '/practice/$challengeId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSlugRoute = AppProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningSubjectIndexRoute = AppLearningSubjectIndexRouteImport.update({
  id: '/learning/$subject/',
  path: '/learning/$subject/',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningSubjectTopicIdRoute =
  AppLearningSubjectTopicIdRouteImport.update({
    id: '/learning/$subject/$topicId',
    path: '/learning/$subject/$topicId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AppAchievementsRoute
  '/admin': typeof AppAdminRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/help': typeof AppHelpRoute
  '/mentor': typeof AppMentorRoute
  '/portfolio': typeof AppPortfolioRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/practice/$challengeId': typeof AppPracticeChallengeIdRoute
  '/projects/$slug': typeof AppProjectsSlugRoute
  '/learning/': typeof AppLearningIndexRoute
  '/practice/': typeof AppPracticeIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/learning/$subject/$topicId': typeof AppLearningSubjectTopicIdRoute
  '/learning/$subject/': typeof AppLearningSubjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AppAchievementsRoute
  '/admin': typeof AppAdminRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/help': typeof AppHelpRoute
  '/mentor': typeof AppMentorRoute
  '/portfolio': typeof AppPortfolioRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/practice/$challengeId': typeof AppPracticeChallengeIdRoute
  '/projects/$slug': typeof AppProjectsSlugRoute
  '/learning': typeof AppLearningIndexRoute
  '/practice': typeof AppPracticeIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/learning/$subject/$topicId': typeof AppLearningSubjectTopicIdRoute
  '/learning/$subject': typeof AppLearningSubjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/mentor': typeof AppMentorRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/practice/$challengeId': typeof AppPracticeChallengeIdRoute
  '/_app/projects/$slug': typeof AppProjectsSlugRoute
  '/_app/learning/': typeof AppLearningIndexRoute
  '/_app/practice/': typeof AppPracticeIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/learning/$subject/$topicId': typeof AppLearningSubjectTopicIdRoute
  '/_app/learning/$subject/': typeof AppLearningSubjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/achievements'
    | '/admin'
    | '/attendance'
    | '/dashboard'
    | '/help'
    | '/mentor'
    | '/portfolio'
    | '/profile'
    | '/settings'
    | '/practice/$challengeId'
    | '/projects/$slug'
    | '/learning/'
    | '/practice/'
    | '/projects/'
    | '/learning/$subject/$topicId'
    | '/learning/$subject/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/achievements'
    | '/admin'
    | '/attendance'
    | '/dashboard'
    | '/help'
    | '/mentor'
    | '/portfolio'
    | '/profile'
    | '/settings'
    | '/practice/$challengeId'
    | '/projects/$slug'
    | '/learning'
    | '/practice'
    | '/projects'
    | '/learning/$subject/$topicId'
    | '/learning/$subject'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/_app/achievements'
    | '/_app/admin'
    | '/_app/attendance'
    | '/_app/dashboard'
    | '/_app/help'
    | '/_app/mentor'
    | '/_app/portfolio'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/practice/$challengeId'
    | '/_app/projects/$slug'
    | '/_app/learning/'
    | '/_app/practice/'
    | '/_app/projects/'
    | '/_app/learning/$subject/$topicId'
    | '/_app/learning/$subject/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mentor': {
      id: '/_app/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AppMentorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learning/': {
      id: '/_app/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof AppLearningIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/': {
      id: '/_app/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AppPracticeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/$challengeId': {
      id: '/_app/practice/$challengeId'
      path: '/practice/$challengeId'
      fullPath: '/practice/$challengeId'
      preLoaderRoute: typeof AppPracticeChallengeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$slug': {
      id: '/_app/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof AppProjectsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learning/$subject/': {
      id: '/_app/learning/$subject/'
      path: '/learning/$subject'
      fullPath: '/learning/$subject/'
      preLoaderRoute: typeof AppLearningSubjectIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learning/$subject/$topicId': {
      id: '/_app/learning/$subject/$topicId'
      path: '/learning/$subject/$topicId'
      fullPath: '/learning/$subject/$topicId'
      preLoaderRoute: typeof AppLearningSubjectTopicIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHelpRoute: typeof AppHelpRoute
  AppMentorRoute: typeof AppMentorRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppPracticeChallengeIdRoute: typeof AppPracticeChallengeIdRoute
  AppProjectsSlugRoute: typeof AppProjectsSlugRoute
  AppLearningIndexRoute: typeof AppLearningIndexRoute
  AppPracticeIndexRoute: typeof AppPracticeIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppLearningSubjectTopicIdRoute: typeof AppLearningSubjectTopicIdRoute
  AppLearningSubjectIndexRoute: typeof AppLearningSubjectIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAdminRoute: AppAdminRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHelpRoute: AppHelpRoute,
  AppMentorRoute: AppMentorRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppPracticeChallengeIdRoute: AppPracticeChallengeIdRoute,
  AppProjectsSlugRoute: AppProjectsSlugRoute,
  AppLearningIndexRoute: AppLearningIndexRoute,
  AppPracticeIndexRoute: AppPracticeIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppLearningSubjectTopicIdRoute: AppLearningSubjectTopicIdRoute,
  AppLearningSubjectIndexRoute: AppLearningSubjectIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
